apiVersion: v1
kind: Service
metadata:
  name: hellowold
  labels:
    app: hellowold
spec:
  type: NodePort
  selector:
    app: hellowold
  ports:
    - protocol: TCP
      targetPort: 8080
      port: 8080
      nodePort: 30080
